services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reading-recommendation-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - reading-recommendation-network
    volumes:
      - ./src:/usr/src/app/src
      - node_modules:/usr/src/app/node_modules

  postgres:
    image: postgres:16-alpine
    container_name: reading-recommendation-postgres-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - reading-recommendation-network

networks:
  reading-recommendation-network:
    driver: bridge

volumes:
  postgres_data:
  node_modules:
